### ISSUE TITLE
Uploaded Replays

### ISSUE THREAD

**Issue by DSFTWAfocus** [ipax77/dsstats#137]
But my rating doesn't seem to have appeared on the website. How do I fix?

**Comment by ipax77** [comment]
Did you press the "Upload" button?
![image](https://user-images.githubusercontent.com/46007167/210374991-f1574dbc-b899-4e74-b698-7c28a5b5d19b.png)

**Comment by DSFTWAfocus** [comment]
Yes, I did. I uploaded 1500 replays last night.

Does it take time?

**Comment by DSFTWAfocus** [comment]
Ignore, I know show on the website. Maybe it just took time.

**Comment by ipax77** [comment]
It takes max 1h to show on the website. Ty for uploading!

**Comment by DSFTWAfocus** [comment]
Appreciate the website!
