### ISSUE TITLE
Preparation for seasonal rating

### ISSUE THREAD

**Issue by ipax77** [ipax77/dsstats#138]
Prepare the rating-generation, so it can handle multiple replays and store additional (seasonal, time based) ratings in the database.

**Comment by ipax77** [comment]
@Firestorm-253 if you want we can do a session together, again. Otherwise I will try to implement it.

**Comment by ipax77** [comment]
I think it would be great to have seasonal ratings at some point.

**Comment by Firestorm-253** [comment]
> I think it would be great to have seasonal ratings at some point.

alright, i mean we should do a new starting point for either 01.02.21 or 01.01.23 anyway, as soon as the merge is done.
