### ISSUE TITLE
Thumbnail

### ISSUE THREAD

**Issue by Firestorm-253** [ipax77/dsstats#192]
![DEA31A11-9BC7-4A2C-AD67-AE7443013C87](https://user-images.githubusercontent.com/115934153/214909451-948bd878-c50b-440c-a1fd-8ac193ba6931.jpeg)

something similar showing an instant image of replay-details, leaderboard, etc when a particular link is being sent.

**Comment by ipax77** [comment]
As far as my research is atm you would have to [prerender every page](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly) and provide some dynamic image in the title/meta information.
