### ISSUE TITLE
ELO - Rework

### ISSUE THREAD

**Issue by Firestorm-253** [ipax77/dsstats#250]
- Confidence will be replaced by Deviation
- Rating and Deviation will form a Distribution for each Player
- Team Distribution will be the sum of the Player’s Distributions
- ELO will be replaced by Team-Distribution Subtraction (Match-Prediction)
- Rating-Change will be dependent on the the Match-Prediction & Player-Deviation & Match-Deviation

**Comment by ipax77** [comment]
Please take into account, that all ratings will be produced from the new [microservice ](https://github.com/ipax77/dsstats/tree/microservice/src/micRatings)
