### ISSUE TITLE
Suggestion for MVP changes

### ISSUE THREAD

**Issue by mrworm1** [ipax77/dsstats#342]
The app uses "total kills" to evaluate who's MVP.  I think a more useful stat can be used.  I call it "effectiveness" and it's generated by "Damage Dealt" + "Damage Taken" = Overall Effect had on the field of play.  Because damage taken and damage dealt are kind of just pseudo values of health on the field of play.

Or maybe it would just be nice to see damage taken and damage dealt in the app because those are the stats I look at most to determine how well I did vs other players.

**Comment by ipax77** [comment]
Yes, you are right, damage dealt/taken would be very nice to have - sadly this information is not available in the replay data, that is why we have to use mineral value killed.

**Comment by mrworm1** [comment]
> Yes, you are right, damage dealt/taken would be very nice to have - sadly this information is not available in the replay data, that is why we have to use mineral value killed.

That makes sense.  Well thank you for listening.  =)
