### ISSUE TITLE
RatingOverTime - GameCount per month

### ISSUE THREAD

**Issue by Firestorm-253** [ipax77/dsstats#41]
Wäre nice die Anzahl Games als Referenz zu sehen.

![8a2d9a21eafd6a51bc1704f79b9b9acc79b7b60b](https://user-images.githubusercontent.com/115934153/202020038-164767ff-5e1e-4736-a1d6-23405e50dc0f.PNG)

**Comment by ipax77** [comment]
implemented with #107
